new
DashaKS25/Medical_blog pull request #2
Opened 2023-08-02 13:00 UTC by DashaKS25

2023-08-02 13:06 UTC, shorodilov requested changes
Потребує виправлень.

2023-08-02 13:06 UTC, shorodilov commented on medapp/admin.py
> +admin.site.register(Article)
А де інші моделі?

2023-08-02 13:06 UTC, shorodilov commented on medapp/models.py
> +    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
Ліпше назвати `author`.

2023-08-02 13:06 UTC, shorodilov commented on medapp/models.py
> +    prefer = models.BooleanField(default=False)
Це поле не знадобиться.
Сама наявність зв'язку сприймається як `prefer`.

2023-08-02 13:06 UTC, shorodilov commented on medapp/models.py
> +class Topic(models.Model):
Ця модель має мати зв'язок з користувачамі.

2023-08-02 13:17 UTC, DashaKS25 commented on medapp/models.py
> +    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
created_at на  author?

2023-08-02 13:27 UTC, shorodilov commented on medapp/models.py
> +    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
Це коментар до 29-го рядка

2023-08-02 13:50 UTC, shorodilov requested changes
Зв'язок має містити інформацію про необхідність повідомлень (`notify`).

2023-08-02 13:50 UTC, shorodilov commented on medapp/models.py
> +    users = models.ManyToManyField(UserModel)
Згідно завдання, зв'язок має містити поле `notify`.

2023-08-02 21:38 UTC, shorodilov requested changes
Трошки файл залежностей битий.
![image](https://github.com/DashaKS25/Medical_blog/assets/22391544/5f6448ba-b010-4969-a3bf-b3554e214b10)

І потрібно виправити міграції, бо падають з помилкою.

2023-08-03 19:24 UTC, shorodilov reviewed
lgtm

2023-08-03 19:24 UTC, shorodilov approved these changes
lgtm

2023-08-03 19:26 UTC, merged